name: Simple

author: yourname

main: simple.Simple

commands:
    simple:
        description: Your description goes here
        usage: Usage of the command goes here
    simple_admin:
        description: Your description goes here
        usage: Usage of the command goes here

version: 0.1

