name: SkyCmd

author: AndyHunt, Learn to Program with Minecraft Plugins
website: http://pragprog.com/book/ahmine

main: skycmd.SkyCmd

commands:
    sky:
        description: Fling nearby creepers into the air
    squidbomb:
        description: drop 10 squid on your head
    ocelotbomb:
        description: drop 10 ocelots on your head

version: 0.1
